"""init tables symbols & klines

Revision ID: dc521ab6fe6c
Revises: 
Create Date: 2025-09-21 02:46:40.258286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc521ab6fe6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('quote_asset_volume', sa.Float(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_kline')
    )
    op.create_index(op.f('ix_klines_interval'), 'klines', ['interval'], unique=False)
    op.create_index('ix_klines_sym_intime', 'klines', ['symbol', 'interval', 'open_time'], unique=False)
    op.create_index(op.f('ix_klines_symbol'), 'klines', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('base', sa.String(length=20), nullable=False),
    sa.Column('quote', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbols')
    op.drop_index(op.f('ix_klines_symbol'), table_name='klines')
    op.drop_index('ix_klines_sym_intime', table_name='klines')
    op.drop_index(op.f('ix_klines_interval'), table_name='klines')
    op.drop_table('klines')
    # ### end Alembic commands ###
